---
title: "HW 02"
subtitle: "Due Thursday, October 15, 11:59 PM"
author: "Matthew Xiao"
output: pdf_document
---

```{r load-packages-data, warning=FALSE, message=FALSE}
library(tidyverse)
licorice <- read_csv("data/licorice.csv") 
```

### Exercise 1

```{r ex-1}
c_licorice <- licorice %>% filter(!is.na(pacu30min_throatPain))

n_sims <- 1000
set.seed(1)
boot_dist = numeric(n_sims)

for (i in 1:n_sims){
  set.seed(i)
  indices <- sample(1:nrow(c_licorice), replace = TRUE)
  boot_mean <- c_licorice %>%
    slice(indices) %>%
    summarize(boot_meean = mean(pacu30min_throatPain)) %>% pull()
  boot_dist[i] = boot_mean
  
  
  
}
boot_means <- tibble(boot_dist)
boot_means %>% summarize(Lower = quantile(boot_dist, 0.025),
                         Upper = quantile(boot_dist, 0.975)) %>% 
  knitr::kable()
t.test(c_licorice$pacu30min_throatPain, conf.level = .95)
```

### Exercise 2

```{r ex-2 base}

b_licorice <- licorice %>% summarize(mean_b = mean(preOp_calcBMI))

set.seed(2)
n_sims <- 2000
boot_dist = numeric(n_sims) 
for(i in 1:n_sims){ 
  set.seed(i) 
  indices <- sample(1:nrow(licorice), replace = T)
  boot_mean <- licorice %>%
    slice(indices) %>%                    
    summarize(boot_mean = mean(preOp_calcBMI)) %>% 
    pull()
  
  boot_dist[i] <- boot_mean 
} 
mu_0 = 26
boot_means <- tibble(boot_dist)

offset <- boot_means %>% 
  summarize(mu_0 - mean(boot_dist) )%>% pull()
boot_means <- tibble(boot_dist)
boot_means %>% summarize(Lower = quantile(boot_dist, 0.025),
                         Upper = quantile(boot_dist, 0.975)) %>% 
  knitr::kable()
boot_means <- boot_means %>% 
  mutate(shifted_means = boot_dist+offset)
ggplot(data = boot_means, aes(x = shifted_means)) +
  geom_histogram(binwidth = 0.1, color = "darkblue", fill = "skyblue") + 
  labs(x = "Mean of BMI", 
       y = "Count",
       title = "The graph displays the null distribution for 
       the mean BMI of the Preoperation Patients with the asumption that the 
       mean BMI is 26.") +
  geom_vline(xintercept = quantile(boot_means$shifted_means, 0.025), 
             lwd = 2, 
             color = "black") +
  geom_vline(xintercept = quantile(boot_means$shifted_means, 0.975),
             lwd= 2,
             color = "black")


obs <- licorice %>% 
  summarize(mean(preOp_calcBMI)) %>%
  pull()
dif <- mu_0 - obs
boot_means <- boot_means %>%
  mutate(shifted_means = boot_dist + offset)

boot_means1 <- boot_means %>%
  mutate(extreme = ifelse(shifted_means <=obs| 
                            shifted_means >=mu_0 + dif, 1,0))%>%
  count(extreme) %>% 
  mutate(prob = n / sum(n)) %>% 
  select(prob) %>% 
  slice(2)
boot_means1 %>% knitr::kable()

```

### Exercise 3

```{r ex-3}

B_pain <- c_licorice %>% 
  mutate(asapain = ifelse(pacu30min_throatPain >0, 1, 0)) 


t.test(B_pain$preOp_asa ~ asapain, 
       data = B_pain,
       mu = 0,
       var.equal = FALSE,
       alternative = "two.sided",
       conf.level = 0.95)







```

### Exercise 4

```{r ex-4}
t.test(pacu30min_throatPain ~ treat, 
       data = c_licorice,
       mu = 0,
       var.equal = FALSE,
       alternative = "greater",
       conf.level = 0.95)


```


### Exercise 5

```{r ex-5}
set.seed(5)
cc_licorice <- c_licorice %>% 
  mutate(pain = ifelse(pacu30min_throatPain >0 | pacu30min_swallowPain >0, 1, 0)) 
licorice_l <- cc_licorice %>% 
  filter(treat == 0 ) 
sugar <- cc_licorice %>% 
  filter(treat == 1 )
n_sims <- 2000
boot_diffs <- numeric(n_sims)


for(i in 1:n_sims){
  # create indices
  indices_h <- sample(1:nrow(licorice_l), replace = T)
  indices_p <- sample(1:nrow(sugar), replace = T)
  # bootstrap est. group means
  temp_h <- licorice_l %>% 
    slice(indices_h) %>% 
    summarize(mean1 = mean(pain)) %>% 
    select(mean1) %>% 
    pull()
  temp_p <- sugar %>% 
    slice(indices_p) %>% 
    summarize(mean_jitter = mean(pain)) %>% 
    select(mean_jitter) %>% 
    pull()

  boot_diffs[i] <- temp_h - temp_p
}
boot_diffs <- tibble(diffs = boot_diffs)
boot_diffs %>% 
  summarize(lower = quantile(diffs, 0.025),
            upper = quantile(diffs, 0.975))
obs_diff <- boot_diffs %>% 
  summarize(obs_diff = mean(diffs)) %>% 
  pull()
offset <- boot_diffs %>% 
  summarize(offset = 0 - mean(diffs)) %>% 
  pull()
null_dist <- boot_diffs %>% 
  mutate(centered_diffs = diffs + offset) %>% 
  select(centered_diffs)
null_dist %>% 
  mutate(extreme = ifelse(centered_diffs > abs(obs_diff), 1, 0)) %>% 
  summarize(p_val = mean(extreme))

```






### Exercise 6




### Exercise 7
TRUE


### Exercise 8

FALSE. Our p-value can not be evidence for, but rather it would only be evidence
that does not reject it can not support. 




### Exercise 9


True




### Exercise 10

TRUE


### Exercise 11

FALSE we can not know for sure


### Exercise 12


TRUE
